db:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  database: "data-battle"
  reset_db: false
ai:
  model: "qwen2.5:7b"
  max_output_tokens: 3000
  host: 'http://localhost:11434/'
  model_classification: 'thenlper/gte-small'
  remake_classification: true
  model_rag: 'thenlper/gte-small'