db:
  host: "postgres"
  port: 5432
  user: "user"
  password: "password"
  database: "data-battle"
ai:
  model: "qwen2.5:7b"
  max_output_tokens: 3000
  host: 'http://ollama:11434/'
  model_classification: 'nlpaueb/bert-base-uncased-eurlex'
  model_rag: 'thenlper/gte-small'